[package]
name = "box-blur-filter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.25.1"

[profile.release]
codegen-units = 1
lto = "fat"